apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: okd-coreos-all-4.13-pipelinerun-
  annotations:
    operator.tekton.dev/prune.skip: "false"
    operator.tekton.dev/prune.resources: "taskrun, pipelinerun"
    operator.tekton.dev/prune.keep: "1"
    operator.tekton.dev/prune.strategy: "keep"
spec:
  params:
    - name: repo
      value: "https://github.com/openshift/os.git"
    - name: branch
      value: "master"
    - name: variant
      value: "scos"     
    - name: version
      value: "4.13"
    - name: rpm-artifacts-image
      value: "registry.ci.openshift.org/origin/4.13:artifacts"
    - name: target-registry
      value: "quay.io/okd"
    - name: baseos-container-image-name
      value: "centos-stream-coreos-9"
    - name: extensions-container-image-name
      value: "centos-stream-coreos-9-extensions"
    - name: tag-latest
      value: "false"
  pipelineRef:
    name: okd-coreos-all
  timeouts:
    pipeline: "4h0m0s"
    tasks: "1h30m0s"
  workspaces:
    - name: registry-credentials
      secret:
        secretName: okd-scos-robot-pull-secret
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          storageClassName: ocs-external-storagecluster-ceph-rbd
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 40Gi
